### ISSUE TITLE
Comments and request for more detail

### ISSUE THREAD

**Issue by wildbunny** [john-connor/papers#1]
Hi John,

This sparked my interest, but I'd like to know more:

*) You mention the three tier P2P network, but there is no description of what distinguishes a client, a peer and a super peer
*) You mention sybil attack, but there is no description of why sybil attack might be a concern for this technique
*) The mempool consensus is also lacking a description, which seems key to this paper

Cheers, Paul.

**Comment by john-connor** [comment]
I've added definitions for the three tiers. Also, I mention that Sybil attacks are of no concern because of the routing table used. The transaction pool and routing, consensus and storage layers are out of the scope of this document but I will add references those drafts are written. 8)

Thank you for your support.

**Comment by wildbunny** [comment]
Thanks, John. I'd still like to know why sybil attack is even relevant for the design of the system, as it implies there is some level of trust involved, but I can't find reference to trust in the doc.

For example, the dash whitepaper lists probabilities for sybil attack in their description of master nodes for their 0 confirmation implementation - I just wondered if this design shares a similar set of concerns?

**Comment by john-connor** [comment]
A sybil attack is irrelevant to the network design "The inability to forge identities in the UDP routing layer prevents Sybil attacks".

**Comment by wildbunny** [comment]
Yet is critical to the consensus design? This is the most interesting part of the paper, IMO and requires more robust treatment.

**Comment by john-connor** [comment]
It's a rough draft of a working implementation. Yes, it will see more revisions.

**Comment by wildbunny** [comment]
Understood. I look forward to reading more about the mempool consensus and the role that the different node types have to play in all this.
